"""empty message

Revision ID: 0bb076d3f9a7
Revises: 8327c548059f
Create Date: 2019-01-27 01:23:03.029346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb076d3f9a7'
down_revision = '8327c548059f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('cancelled', sa.Boolean(), nullable=False))
    op.add_column('transaction', sa.Column('fulfilled', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('transaction', 'fulfilled')
    op.drop_column('transaction', 'cancelled')
    # ### end Alembic commands ###
