"""empty message

Revision ID: 8327c548059f
Revises: 5596da4479dc
Create Date: 2019-01-20 19:31:36.021508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8327c548059f'
down_revision = '5596da4479dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enabled')
    # ### end Alembic commands ###
